const status = "authenticated";

const categories = [
  {
    id: "1",
    title: "Gaming",
    slug: "Gaming",
    color: "#ffb04f45",
  },
  {
    id: "2",
    title: "Entretainment",
    slug: "Entretainment",
    color: "#7fb88133",
  },
  {
    id: "3",
    title: "TV & Movies",
    slug: "TV & Movies",
    color: "#d1d1d1",
  },
  {
    id: "4",
    title: "Esports",
    slug: "Esports",
    color: "#5e4fff31",
  },
  {
    id: "5",
    title: "Tech",
    slug: "Tech",
    color: "#adf7b6",
  },
  {
    id: "6",
    title: "Others",
    slug: "Others",
    color: "#61dafb",
  },
];

//  const posts = [
//   {
//     id: "1",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js",
//     title: "Next JS",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702391820/nqethq3gzldpty0xmkw3.jpg",
//     views: 100,
//     catSlug: "next-js",
//     cat: {
//       id: "1",
//       title: "Next JS",
//       slug: "next-js",
//       color: "#dddddd",
//     },
//   },
//   {
//     id: "2",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js-with-prisma",
//     title: "Next JS with Prisma",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702275296/swz5vbykpoiilhgmwtus.webp",
//     views: 100,
//     catSlug: "prisma",
//     cat: {
//       id: "2",
//       title: "Prisma",
//       slug: "prisma",
//       color: "#7fb88133",
//     },
//   },

//   {
//     id: "3",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js",
//     title: "Next JS",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702391820/nqethq3gzldpty0xmkw3.jpg",
//     views: 100,
//     catSlug: "next-js",
//     cat: {
//       id: "1",
//       title: "Next JS",
//       slug: "next-js",
//       color: "#dddddd",
//     },
//   },
//   {
//     id: "4",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js-with-prisma",
//     title: "Next JS with Prisma",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702275296/swz5vbykpoiilhgmwtus.webp",
//     views: 100,
//     catSlug: "prisma",
//     cat: {
//       id: "2",
//       title: "Prisma",
//       slug: "prisma",
//       color: "#7fb88133",
//     },
//   },
//   {
//     id: "5",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js",
//     title: "Next JS",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702391820/nqethq3gzldpty0xmkw3.jpg",
//     views: 100,
//     catSlug: "next-js",
//     cat: {
//       id: "1",
//       title: "Next JS",
//       slug: "next-js",
//       color: "#dddddd",
//     },
//   },
//   {
//     id: "6",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js-with-prisma",
//     title: "Next JS with Prisma",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702275296/swz5vbykpoiilhgmwtus.webp",
//     views: 100,
//     catSlug: "prisma",
//     cat: {
//       id: "2",
//       title: "Prisma",
//       slug: "prisma",
//       color: "#7fb88133",
//     },
//   },
//   {
//     id: "7",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js",
//     title: "Next JS",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702391820/nqethq3gzldpty0xmkw3.jpg",
//     views: 100,
//     catSlug: "next-js",
//     cat: {
//       id: "1",
//       title: "Next JS",
//       slug: "next-js",
//       color: "#dddddd",
//     },
//   },
//   {
//     id: "8",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js-with-prisma",
//     title: "Next JS with Prisma",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702275296/swz5vbykpoiilhgmwtus.webp",
//     views: 100,
//     catSlug: "prisma",
//     cat: {
//       id: "2",
//       title: "Prisma",
//       slug: "prisma",
//       color: "#7fb88133",
//     },
//   },
// ];

module.exports = {
  status,
  categories,
  // posts,
};
