name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Cypress E2E Tests
        run: |
          npm run e2e  # Assuming your "e2e" script runs Cypress tests

      - name: Run Cypress Component Tests
        run: |
          npm run component  # Assuming your "component" script runs Cypress tests

      - name: Install Vercel CLI
        run: |
          npm install -g vercel

      - name: Build
        run: |
          npm run build

      - name: Deploy to Vercel
        run: |
          vercel --prod --confirm --token ${{ secrets.VERCEL_TOKEN }}
